// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_translate/test/src/services/initial_locale_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i5;

import 'package:flutter_translate/flutter_translate.dart' as _i3;
import 'package:flutter_translate/src/models/locale_data.dart' as _i4;
import 'package:flutter_translate/src/services/fallback_locale_service.dart'
    as _i9;
import 'package:flutter_translate/src/services/loaders/base/localization_loader.dart'
    as _i2;
import 'package:flutter_translate/src/services/loaders/base/localization_loader_options.dart'
    as _i6;
import 'package:flutter_translate/src/services/locale_persistence_service.dart'
    as _i10;
import 'package:flutter_translate/src/services/localization_service.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocalizationLoader_0 extends _i1.SmartFake
    implements _i2.LocalizationLoader {
  _FakeLocalizationLoader_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterTranslateOptions_1 extends _i1.SmartFake
    implements _i3.FlutterTranslateOptions {
  _FakeFlutterTranslateOptions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocaleData_2 extends _i1.SmartFake implements _i4.LocaleData {
  _FakeLocaleData_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocale_3 extends _i1.SmartFake implements _i5.Locale {
  _FakeLocale_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalizationLoaderOptions_4 extends _i1.SmartFake
    implements _i6.LocalizationLoaderOptions {
  _FakeLocalizationLoaderOptions_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalizationService extends _i1.Mock
    implements _i7.LocalizationService {
  MockLocalizationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalizationLoader get loader => (super.noSuchMethod(
        Invocation.getter(#loader),
        returnValue: _FakeLocalizationLoader_0(
          this,
          Invocation.getter(#loader),
        ),
      ) as _i2.LocalizationLoader);

  @override
  _i3.FlutterTranslateOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeFlutterTranslateOptions_1(
          this,
          Invocation.getter(#options),
        ),
      ) as _i3.FlutterTranslateOptions);

  @override
  bool containsLocale(_i5.Locale? locale) => (super.noSuchMethod(
        Invocation.method(
          #containsLocale,
          [locale],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<Map<String, dynamic>?> loadLocaleData(_i5.Locale? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadLocaleData,
          [locale],
        ),
        returnValue: _i8.Future<Map<String, dynamic>?>.value(),
      ) as _i8.Future<Map<String, dynamic>?>);
}

/// A class which mocks [FallbackLocaleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFallbackLocaleService extends _i1.Mock
    implements _i9.FallbackLocaleService {
  MockFallbackLocaleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.LocaleData> getFallbackLocaleData() => (super.noSuchMethod(
        Invocation.method(
          #getFallbackLocaleData,
          [],
        ),
        returnValue: _i8.Future<_i4.LocaleData>.value(_FakeLocaleData_2(
          this,
          Invocation.method(
            #getFallbackLocaleData,
            [],
          ),
        )),
      ) as _i8.Future<_i4.LocaleData>);

  @override
  _i8.Future<Map<String, dynamic>> loadFallbackLocaleData() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadFallbackLocaleData,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);
}

/// A class which mocks [LocalePersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalePersistenceService extends _i1.Mock
    implements _i10.LocalePersistenceService {
  MockLocalePersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.Locale?> getPreferredLocale() => (super.noSuchMethod(
        Invocation.method(
          #getPreferredLocale,
          [],
        ),
        returnValue: _i8.Future<_i5.Locale?>.value(),
      ) as _i8.Future<_i5.Locale?>);

  @override
  _i8.Future<dynamic> savePreferredLocale(_i5.Locale? locale) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePreferredLocale,
          [locale],
        ),
        returnValue: _i8.Future<dynamic>.value(),
      ) as _i8.Future<dynamic>);
}

/// A class which mocks [FlutterTranslateOptions].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterTranslateOptions extends _i1.Mock
    implements _i3.FlutterTranslateOptions {
  MockFlutterTranslateOptions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Locale get fallbackLocale => (super.noSuchMethod(
        Invocation.getter(#fallbackLocale),
        returnValue: _FakeLocale_3(
          this,
          Invocation.getter(#fallbackLocale),
        ),
      ) as _i5.Locale);

  @override
  List<_i5.Locale> get supportedLocales => (super.noSuchMethod(
        Invocation.getter(#supportedLocales),
        returnValue: <_i5.Locale>[],
      ) as List<_i5.Locale>);

  @override
  bool get autoSave => (super.noSuchMethod(
        Invocation.getter(#autoSave),
        returnValue: false,
      ) as bool);

  @override
  _i3.MissingKeyStrategy get missingKeyStrategy => (super.noSuchMethod(
        Invocation.getter(#missingKeyStrategy),
        returnValue: _i3.MissingKeyStrategy.key,
      ) as _i3.MissingKeyStrategy);

  @override
  _i6.LocalizationLoaderOptions get loaderOptions => (super.noSuchMethod(
        Invocation.getter(#loaderOptions),
        returnValue: _FakeLocalizationLoaderOptions_4(
          this,
          Invocation.getter(#loaderOptions),
        ),
      ) as _i6.LocalizationLoaderOptions);
}
